name: Actions deploy Terraform
run-name: PR Workflow MAIN
on:
  pull_request:
      branches:
        - main
      types:
        - opened
        - edited

jobs:
  terraform:
    name: Deploying Terraform
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
    steps:   

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: autero1/action-terraform@v1.1.0
        with:
          terraform_version: 1.2.8

      - name: Echo AWS_ACCESS_KEY_ID
        run: echo "$AWS_ACCESS_KEY_ID"
      
      - name: Echo AWS_SECRET_ACCESS_KEY
        run: echo "$AWS_SECRET_ACCESS_KEY"

      - name: Acessando pasta ECR
        run: cd ./ecr/

      - name: Interact with Terraform
        run: terraform plan

      - name: Acessando pasta ECS
        run: cd ../ecs/

      - name: Interact with Terraform
        run: terraform plan
      
      - name: Acessando pasta RDS
        run: cd ../rds/

      - name: Interact with Terraform
        run: terraform plan

      - name: Acessando pasta S3
        run: cd ../s3/

      - name: Interact with Terraform
        run: terraform plan