name: Actions deploy Terraform
run-name: PR Workflow MAIN
on:
  pull_request:
      branches:
        - main
      types:
        - closed

env:
  AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{ vars.AWS_SECRET_ACCESS_KEY}}
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION}}

jobs:
  terraform:
    name: Deploying Terraform
    runs-on: ubuntu-latest
    
    steps:   

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: autero1/action-terraform@v1.1.0
        with:
          terraform_version: 1.2.8

      - name: Echo AWS_ACCESS_KEY_ID
        run: echo "$AWS_ACCESS_KEY_ID"
      
      - name: Echo AWS_SECRET_ACCESS_KEY
        run: echo "$AWS_SECRET_ACCESS_KEY"

      - name: Echo AWS_DEFAULT_REGION
        run: echo "$AWS_DEFAULT_REGION"

      - name: Mostando arquivos repo
        run: ls -lh

      - name: Deploying ECR
        run: cd ./ecr && terraform init && terraform plan && terraform apply -auto-approve

      - name: Deploying ECS
        run: cd ./ecs && terraform init && terraform plan && terraform apply -auto-approve
      
      - name: Deploying RDS
        run: cd ./rds && terraform init && terraform plan && terraform apply -auto-approve

      - name: Deploying S3
        run: cd ./s3 && terraform init && terraform plan && terraform apply -auto-approve

      - name: Deploying Gateway
        run: cd ./gateway && terraform init && terraform plan && terraform apply -auto-approve